export default [
  {
    name: "Margarita",
    price: 95,
    ingredients: "ost, tomatsås",
    category: "Prisklass 1",
  },
  {
    name: "Al Tonno",
    price: 95,
    ingredients: "tonfisk, lök",
    category: "Prisklass 1",
  },
  {
    name: "Al Funghi",
    price: 95,
    ingredients: "färska champinjoner",
    category: "Prisklass 1",
  },
  {
    name: "Bologna",
    price: 95,
    ingredients: "köttfärsås",
    category: "Prisklass 2",
  },
  {
    name: "Calzone",
    price: 95,
    ingredients: "skinka",
    category: "Hampus Specialare",
  },
  {
    name: "Vesuvio",
    price: 95,
    ingredients: "skinka",
    category: "Hampus Specialare",
  },
  {
    name: "Margarita",
    price: 95,
    ingredients: "ost, tomatsås",
    category: "Prisklass 1",
  },
  {
    name: "Al Tonno",
    price: 95,
    ingredients: "tonfisk, lök",
    category: "Prisklass 1",
  },
  {
    name: "Al Funghi",
    price: 95,
    ingredients: "färska champinjoner",
    category: "Prisklass 1",
  },
  {
    name: "Bologna",
    price: 95,
    ingredients: "köttfärsås",
    category: "Prisklass 2",
  },
  {
    name: "Calzone",
    price: 95,
    ingredients: "skinka",
    category: "Hampus Specialare",
  },
  {
    name: "Marabou Cookies",
    price: 20,
    ingredients: "kakor",
    category: "Hampus Specialare",
  },
  {
    name: "Vesuvio",
    price: 95,
    ingredients: "skinka",
    category: "Hampus Specialare",
  },
  {
    name: "Monster Juiced",
    price: 120,
    ingredients: "skinka, julmust",
    category: "Hampus Specialare",
  },
  {
    name: "Extra Vesuvio",
    price: 200,
    ingredients: "ingen skinka, ingen ost, utan deg, kall",
    category: "Prisklass 2",
  },
  {
    name: "Peppar Turken",
    price: 115,
    ingredients: "turkisk peppar (mald), hallon",
    category: "Pappa Special",
  },
];
