export default [
  {
    name: "Margarita",
    price: 90,
    ingredients: "cheese, tomato sauce",
    category: "Priceclass 1",
  },
  {
    name: "Al Tonno",
    price: 95,
    ingredients: "tuna, onion",
    category: "Priceclass 1",
  },
  {
    name: "Al Funghi",
    price: 95,
    ingredients: "mushrooms",
    category: "Priceclass 1",
  },
  {
    name: "Bologna",
    price: 95,
    ingredients: "ground beef",
    category: "Priceclass 1",
  },
  {
    name: "Calzone",
    price: 90,
    ingredients: "ham",
    category: "Priceclass 1",
  },
  {
    name: "Vesuvio",
    price: 95,
    ingredients: "ham",
    category: "Priceclass 1",
  },
  {
    name: "Bussola",
    price: 100,
    ingredients: "ham, shrimp",
    category: "Priceclass 1",
  },
  {
    name: "Hawaii",
    price: 95,
    ingredients: "pineapple, ham",
    category: "Priceclass 1",
  },
  {
    name: "Capricciosa",
    price: 95,
    ingredients: "ham, mushrooms",
    category: "Priceclass 1",
  },
  {
    name: "Balanzone",
    price: 100,
    ingredients: "bacon, onion, red pepper",
    category: "Priceclass 1",
  },
  {
    name: "Romana",
    price: 120,
    ingredients: "ham, muchrooms, shrimp",
    category: "Priceclass 2",
  },
  {
    name: "Quattro",
    price: 125,
    ingredients: "ham, shrimp, mushrooms, olives",
    category: "Priceclass 2",
  },
  {
    name: "Pepperoni",
    price: 120,
    ingredients: "pepperoni, mozarella, tomatos",
    category: "Priceclass 2",
  },
  {
    name: "Milan",
    price: 130,
    ingredients: "salami, bacon, red peppers",
    category: "Priceclass 2",
  },
  {
    name: "Chicken Pizza",
    price: 120,
    ingredients: "chicken, curry",
    category: "Priceclass 2",
  },
  {
    name: "Kebabpizza",
    price: 130,
    ingredients: "kebab, onion, fefferoni",
    category: "Priceclass 2",
  },
  {
    name: "Kebabpizza 2",
    price: 130,
    ingredients: "kebab, vegetables",
    category: "Priceclass 2",
  },
  {
    name: "kebabpizza 3",
    price: 130,
    ingredients: "kebab, fries, vegetables",
    category: "Priceclass 2",
  },
  {
    name: "Al Capone",
    price: 120,
    ingredients: "pork, mushrooms, tomato, gorgonzola",
    category: "Priceclass 2",
  },
  {
    name: "CaoCao",
    price: 120,
    ingredients: "pork, onion, red pepper, bearnaise",
    category: "Priceclass 2",
  },
  {
    name: "Leafsteak",
    price: 140,
    ingredients: "vegetables, bearnaise",
    category: "A La Carte",
  },
  {
    name: "Schnitzel",
    price: 150,
    ingredients: "vegetable, truffelsauce",
    category: "A La Carte",
  },
  {
    name: "Chickenfilet",
    price: 130,
    ingredients: "vegetables, currysauce",
    category: "A La Carte",
  },
  {
    name: "Steak with onion",
    price: 170,
    ingredients: "vegetables, red wine sauce",
    category: "A La Carte",
  },
  {
    name: "Pasta Bolognese",
    price: 120,
    ingredients: "meatsauce",
    category: "A La Carte",
  },
  {
    name: "Pasta Carbonara",
    price: 120,
    ingredients: "ham, red pepper, onion",
    category: "A La Carte",
  },
  {
    name: "Kebab Wrap",
    price: 100,
    ingredients: "kebab, vegetables",
    category: "A La Carte",
  },
  {
    name: "Cicken Salad",
    price: 120,
    ingredients: "chicken, vegetables, egg",
    category: "A La Carte",
  },
  {
    name: "Hamburger 90g",
    price: 100,
    ingredients: "fries",
    category: "A La Carte",
  },
  {
    name: "Hamburger 150g",
    price: 120,
    ingredients: "fries",
    category: "A La Carte",
  },
];
