export default [
  { name: "Margarita", price: 95, ingredients: "ost, tomatsås" },
  { name: "Al Tonno", price: 95, ingredients: "tonfisk, lök" },
  { name: "Al Funghi", price: 95, ingredients: "färska champinjoner" },
  { name: "Bologna", price: 95, ingredients: "köttfärsås" },
  { name: "Calzone", price: 95, ingredients: "skinka" },
  { name: "Vesuvio", price: 95, ingredients: "skinka" },
  { name: "Margarita", price: 95, ingredients: "ost, tomatsås" },
  { name: "Al Tonno", price: 95, ingredients: "tonfisk, lök" },
  { name: "Al Funghi", price: 95, ingredients: "färska champinjoner" },
  { name: "Bologna", price: 95, ingredients: "köttfärsås" },
  { name: "Calzone", price: 95, ingredients: "skinka" },
  { name: "Vesuvio", price: 95, ingredients: "skinka" },
  { name: "Margarita", price: 95, ingredients: "ost, tomatsås" },
  { name: "Al Tonno", price: 95, ingredients: "tonfisk, lök" },
  { name: "Al Funghi", price: 95, ingredients: "färska champinjoner" },
  { name: "Bologna", price: 95, ingredients: "köttfärsås" },
  { name: "Calzone", price: 95, ingredients: "skinka" },
  { name: "Vesuvio", price: 95, ingredients: "skinka" },
];
